CREATE TABLE notes.note
(
    ID BIGINT NOT NULL PRIMARY KEY,
    NOTE_TEXT CHARACTER VARYING(255) NOT NULL,
    TEXT_COLOR CHARACTER VARYING(255) NOT NULL,
    BG_COL CHARACTER VARYING(255) NOT NULL
);

